apiVersion: v1
kind: Pod
metadata: # Dictionary type, contains key and values
  name: test-pod
  labels:
    app: test-app
spec:
  containers: #List type, it can contain multiple containers field.
    - name: test-app
      image: busybox
      ports:
        - containerPort: 80
